pluginManagement {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.name = "LANFileViewer"

include ':app', ':preferences', ':common', ':common-android'

project(':common').projectDir = file('Common-Library/common')
project(':common-android').projectDir = file('Common-Library/common-android')
project(':preferences').projectDir = file('Common-Library/preferences')